# Generated by Django 2.1.5 on 2019-01-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_comment_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
